language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js: 8
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run coverage

# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/
